config/routes.rb
Rails.application.routes.draw do
  # get 'books/index'
  # get 'books/show'
  # get 'books/new'
  # get 'books/create'
  # get 'books/edit'
  # get 'books/update'
  # get 'books/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'students#index'
  resources :books
  resources :students
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: { message: 'judul harus diisi' }
  validates :description, presence: { message: 'deskripsi harus diisi' }, length: { minimum: 4, message: 'minimal 4 karakter'}
  validates :price, presence: { message: 'harga harus diisi' }, numericality: {only_integer: true}
  validates :page, presence: { message: 'halaman harus diisi' }, numericality: { only_integer: true, greater_than_or_equal_to: 10, message: 'jumlah halaman harus >=10'}
  validates :year, presence: { message: 'tahun harus diisi' }, numericality: {only_integer: true, greater_than_or_equal_to: 1900, message: 'tahun berupa 4 digit angka'}
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def book_params
    params.require(:book).permit(:title, :description, :price, :page, :year)
  end

  def current_book
    Book.find params[:id]
  end

  def index
    @title = 'Buku'
    @books = Book.all
  end

  def show
    @book = current_book
  end
  def edit
    @book = current_book
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path, notice: "Buku #{@book.title} berhasil disimpan"
    else
      render 'new'      
    end
  end


  def update
    @book = current_book
    if @book.update book_params
      redirect_to books_path, notice: 'Berhasil memperbarui data buku'
    else
      render 'edit'
    end
  end

  def destroy
    @book = current_book
    @book.destroy
    redirect_to books_path, notice: 'Berhasil menghapus data buku'
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def object_params
    params.require(:student).permit(:name, :nim, :email, :phone, :address)
  end

  def current_student
    Student.find params[:id]
  end

  def index
    @title = 'Siswa'
    @students = Student.all
  end
  def show
    @student = Student.find(params[:id])
  end
  def edit
    @student = Student.find(params[:id])
  end
  def new
    @student = Student.new
  end
  def create
    @object = Student.new(object_params)
    if @object.save
      redirect_to students_path, notice: "Siswa #{@object.name} berhasil disimpan"
    else
      render 'new'      
    end
  end
  def update
    @student = current_student
    if @student.update object_params
      redirect_to students_path, notice: 'Berhasil memperbarui data siswa'
    else
      render 'edit'
    end
  end
  def destroy
    @student = current_student
    @student.destroy
    redirect_to students_path, notice: 'Berhasil menghapus data siswa'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/books/_form.html.erb
<!--
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |error| %>
    <div class="alert alert-danger">
      <%= error %>
    </div>
  <% end %>
<% end %>
-->
<%= form_for @book do |f| %>
  <div>
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
    <% if @book.errors[:title] %>
      <%= @book.errors[:title].join(', ') %>
    <% end %>
  </div>
  <div>
    <%= f.label :description %>
    <br>
    <%= f.text_field :description %>
    <% if @book.errors[:description] %>
      <%= @book.errors[:description].join(', ') %>
    <% end %>
  </div>
  <div>
    <%= f.label :price %>
    <br>
    <%= f.text_field :price %>
    <% if @book.errors[:price] %>
      <%= @book.errors[:price].join(', ') %>
    <% end %>
  </div>
  <div>
    <%= f.label :page %>
    <br>
    <%= f.text_field :page %>
    <% if @book.errors[:page] %>
      <%= @book.errors[:page].join(', ') %>
    <% end %>
  </div>
  <div>
    <%= f.label :year %>
    <br>
    <%= f.text_field :year %>
    <% if @book.errors[:year] %>
      <%= @book.errors[:year].join(', ') %>
    <% end %>
  </div>
  <div>
    <%= f.submit button_text %>
    <br>
  </div>
<% end %>

app/views/books/create.html.erb
<h1>Books#create</h1>
<p>Find me in app/views/books/create.html.erb</p>

app/views/books/destroy.html.erb
<h1>Books#destroy</h1>
<p>Find me in app/views/books/destroy.html.erb</p>

app/views/books/edit.html.erb
<h3>
  Edit Buku
</h3>
<%= link_to 'Lihat Buku', books_path %> |
<%= link_to 'Tambah Buku', new_book_path %>
<%#= render 'form' %>
<%= render partial: 'form', locals: {button_text: 'Simpan perubahan'} %>

app/views/books/index.html.erb
<h3>
  Data
  <small><%= @title %></small>
</h3>
<%= link_to 'Lihat Buku', books_path %> |
<%= link_to 'Tambah Buku', new_book_path %>
<table class="table table-hover table-striped table-sm">
  <thead>
    <tr>
      <td></td>
      <td>Title</td>
      <td>Description</td>
      <td>Price</td>
      <td>Pages</td>
      <td>Year</td>
    </tr>
  </thead>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to "Detail", book_path(book) %> |
          <%= link_to "Edit", edit_book_path(book) %> |
          <%= link_to "Delete", book_path(book), method: :delete, data: {
            confirm: "Buku #{book.title} akan dihapus"
          } %>
        </td>
        <td><%= book.title %></td>
        <td><%= book.description %></td>
        <td><%= book.price %></td>
        <td><%= book.page %></td>
        <td><%= book.year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/new.html.erb
<h3>
  Tambah Buku
</h3>
<%= link_to 'Lihat Buku', books_path %> |
<%= link_to 'Tambah Buku', new_book_path %>
<%#= render 'form' %>
<%= render partial: 'form', locals: {button_text: 'Simpan perubahan'} %>

app/views/books/show.html.erb
<h3>
  Detail Buku
  <small>
    <%= @book.title %>
  </small>
</h3>
<%= link_to 'Lihat Buku', books_path %> |
<%= link_to 'Tambah Buku', new_book_path %>
<table class="table table-sm">
  <tbody>
    <tr>
      <td>Name</td>
      <td><%= @book.title %></td>
    </tr>
    <tr>
      <td>Description</td>
      <td><%= @book.description %></td>
    </tr>
    <tr>
      <td>Price</td>
      <td><%= @book.price %></td>
    </tr>
    <tr>
      <td>Pages</td>
      <td><%= @book.page %></td>
    </tr>
    <tr>
      <td>Year</td>
      <td><%= @book.year %></td>
    </tr>
  </tbody>
</table>

app/views/books/update.html.erb
<h1>Books#update</h1>
<p>Find me in app/views/books/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/books">Books <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/students">Students</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# additional %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/students/_form.html.erb
<% if @student.errors.any? %>
  <% @student.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>
<% end %>
<%= form_for @student do |f| %>
  <div>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
    <% if @student.errors[:name] %>
      <%= @student.errors[:name].join(', ') %>
    <% end %>
  </div>
  <div>
    <%= f.label :nim %>
    <br>
    <%= f.text_field :nim %>
    <% if @student.errors[:nim] %>
      <%= @student.errors[:nim].join(', ') %>
    <% end %>
  </div>
  <div>
    <%= f.label :email %>
    <br>
    <%= f.text_field :email %>
    <% if @student.errors[:email] %>
      <%= @student.errors[:email].join(', ') %>
    <% end %>
  </div>
  <div>
    <%= f.label :phone %>
    <br>
    <%= f.text_field :phone %>
    <% if @student.errors[:phone] %>
      <%= @student.errors[:phone].join(', ') %>
    <% end %>
  </div>
  <div>
    <%= f.label :address %>
    <br>
    <%= f.text_field :address %>
    <% if @student.errors[:address] %>
      <%= @student.errors[:address].join(', ') %>
    <% end %>
  </div>
  <div>
    <%= f.submit button_text %>
    <br>
  </div>
<% end %>

app/views/students/edit.html.erb
<h3 class="capitalize">edit siswa</h3>
<%= link_to 'Lihat Siswa', students_path, class: 'link' %> |
<%= link_to 'Tambah Siswa', new_student_path, class: 'link' %>
<%#= render 'form' %>
<%= render partial: 'form', locals: {button_text: 'Simpan perubahan'} %>

app/views/students/index.html.erb
<div class="table-container">
  <h3>
    Data
    <small><%= @title %></small>
  </h3>
  <%= link_to 'Lihat Siswa', students_path, class: 'link' %> |
  <%= link_to 'Tambah Siswa', new_student_path, class: 'link' %>
  <table id="dynamic-table" class="table table-striped table-hover table-sm">
    <thead>
      <tr>
        <td></td>
        <td>Nama</td>
        <td>NIM</td>
        <td>Email</td>
        <td>Telepon</td>
        <td>Alamat</td>
      </tr>
    </thead>
    <tbody>
      <% @students.each do |s| %>
        <tr>
          <td>
            <%= link_to 'Detail', student_path(s), class: 'link' %> |
            <%= link_to 'Edit', edit_student_path(s), class: 'link' %> |
            <%= link_to "Delete", student_path(s), method: :delete, data: {
              confirm: "Siswa #{s.name} akan dihapus"
            } %>
          </td>
          <td><%= s.name %></td>
          <td><%= s.nim %></td>
          <td><%= s.email %></td>
          <td><%= s.phone %></td>
          <td><%= s.address %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/new.html.erb
<h3 class="capitalize">tambah siswa</h3>
<%= link_to 'Lihat Siswa', students_path, class: 'link' %> |
<%= link_to 'Tambah Siswa', new_student_path, class: 'link' %>
<%#= render 'form' %>
<%= render partial: 'form', locals: {button_text: 'Simpan perubahan'} %>

app/views/students/show.html.erb
<h3>
  <%= @student.name %>
</h3>
<%= link_to 'Lihat Siswa', students_path %> |
<%= link_to 'Tambah Siswa', new_student_path %>
<table class="table table-sm">
  <tbody>
    <tr>
      <td>Name</td>
      <td><%= @student.name %></td>
    </tr>
    <tr>
      <td>Email</td>
      <td><%= @student.email %></td>
    </tr>
    <tr>
      <td>Telephone</td>
      <td><%= @student.phone %></td>
    </tr>
    <tr>
      <td>Address</td>
      <td><%= @student.address %></td>
    </tr>
  </tbody>
</table>